# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WQBwSPsgMAHlQeNe4e9VCSFHqGUh3nTRAx8E3CVtTA9imNoUjIIG/UXE9WIfJ6GNVYT6uWfte7CXE5AGLWBExu/cTHm1FqkXoannwf6vhcdjq2+cCb59h+KRZanWTXV67Mbglt+ajdWtisoHtJpwcgFGLSEDee2IJ5T8di8cCIghlGb3QNsQJPaEdUx//N/YiKNf+4viewT4F2+/2TAX0tt2MvjEO+5Jz05dS+93VqtuEo/GEhMyEphKBok8xFXxImJjSQ2m+j6innAGke4eWNpc+iik6dAmESnXXU45ecLC4kPMQNPdWFIFoi3Jcy8/xXvj/krVk4VsFc+s8vGMvcY2cwKY9qO1V/feYUxaor4C6o57NTm8yc8ZBCf7MUONDrxOFesl6RmdjVIyZOo5t3pSfNntxN3GbagTmVVnJlXC7TUhNehyqUXtJ3Ww4qxJDtUNhH0dvAID60sTttjCHDctyeJmeWn+wAvOp9CEvXcReZ+AZ2/irOCqsXDQDyEalY9xK2dgj/5xvVYfIgT/P+Zk77UZrWVY/0ZTdSUPv6GeJvDq1Q2ZEyCFf2pxUX/4ZmBFwSc5GFlZItgkyXZlTI9r/+W7HKB7gc0nZ9/wdv3zseEwjiZvI6Fqr/FONgtwTicOQOfFxNYu4vO7cg5mDMjrWNrOI2JKG0lTviNGOy4="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_mpimpichnumpy1.16python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpimpichnumpy1.16python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpimpichnumpy1.16python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpimpichnumpy1.18python3.6.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompinumpy1.16python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompinumpy1.16python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompinumpy1.16python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompinumpy1.18python3.6.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpinumpy1.16python3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpinumpy1.16python3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpinumpy1.16python3.8.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpinumpy1.18python3.6.____73_pypy UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi